"""add_multi_tenant_fields

Revision ID: 98b4c479c80f
Revises: 0001_nombre_lubricentro
Create Date: 2026-01-07 16:25:08.586504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b4c479c80f'
down_revision: Union[str, Sequence[str], None] = '0001_nombre_lubricentro'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_clientes_user_id_usuarios'), 'usuarios', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comprobantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_comp_pv_num'))
        batch_op.create_index('idx_comp_user_pv_num', ['user_id', 'punto_venta', 'numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_comprobantes_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_comprobantes_user_id_usuarios'), 'usuarios', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('stock_categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_stock_categorias_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_stock_categorias_user_id_usuarios'), 'usuarios', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('stock_productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_stock_productos_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_stock_productos_user_id_usuarios'), 'usuarios', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_turnos_fecha_hora'))
        batch_op.create_index('idx_turnos_user_fecha_hora', ['user_id', 'fecha', 'hora'], unique=True)
        batch_op.create_index(batch_op.f('ix_turnos_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_turnos_user_id_usuarios'), 'usuarios', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_fondo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color_tematica', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color_tematica2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color_letras', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tema', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('idioma', sa.String(), nullable=True))
        batch_op.alter_column('nombre_lubricentro',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nombre_lubricentro',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('idioma')
        batch_op.drop_column('tema')
        batch_op.drop_column('color_letras')
        batch_op.drop_column('color_tematica2')
        batch_op.drop_column('color_tematica')
        batch_op.drop_column('color_fondo')

    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_turnos_user_id_usuarios'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_turnos_user_id'))
        batch_op.drop_index('idx_turnos_user_fecha_hora')
        batch_op.create_index(batch_op.f('idx_turnos_fecha_hora'), ['fecha', 'hora'], unique=1)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('stock_productos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stock_productos_user_id_usuarios'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_stock_productos_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('stock_categorias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stock_categorias_user_id_usuarios'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_stock_categorias_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('comprobantes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comprobantes_user_id_usuarios'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comprobantes_user_id'))
        batch_op.drop_index('idx_comp_user_pv_num')
        batch_op.create_index(batch_op.f('idx_comp_pv_num'), ['punto_venta', 'numero'], unique=1)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_clientes_user_id_usuarios'), type_='foreignkey')

    # ### end Alembic commands ###
